/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: /home/abhijeet/Desktop/Svan_project/Svan/src/robonex_ai/robonex_ai/JoyData.idl
  Source: JoyData.cpp
  Cyclone DDS: v11.0.1

*****************************************************************/
#include "JoyData.hpp"

#include <org/eclipse/cyclonedds/util/ostream_operators.hpp>

namespace xterra
{
namespace msg
{
namespace dds_
{
std::ostream& operator<<(std::ostream& os, ::xterra::msg::dds_::JoyData_ const& rhs)
{
  (void) rhs;
  os << "[";
  os << "priority: " << rhs.priority();
  os << ", axes: " << rhs.axes();
  os << ", buttons: " << rhs.buttons();
  os << "]";
  return os;
}

} //namespace dds_

} //namespace msg

} //namespace xterra

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
const propvec &get_type_props<::xterra::msg::dds_::JoyData_>() {
  static std::mutex mtx;
  static propvec props;
  static std::atomic_bool initialized {false};
  key_endpoint keylist;
  if (initialized.load(std::memory_order_relaxed))
    return props;
  std::lock_guard<std::mutex> lock(mtx);
  if (initialized.load(std::memory_order_relaxed))
    return props;
  props.clear();

  props.push_back(entity_properties_t(0, 0, false, bit_bound::bb_unset, extensibility::ext_final));  //root
  props.push_back(entity_properties_t(1, 0, false, get_bit_bound<uint8_t>(), extensibility::ext_final, false));  //::priority
  props.push_back(entity_properties_t(1, 1, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::axes
  props.push_back(entity_properties_t(1, 2, false, get_bit_bound<uint8_t>(), extensibility::ext_final, false));  //::buttons

  entity_properties_t::finish(props, keylist);
  initialized.store(true, std::memory_order_release);
  return props;
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

