/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: /home/abhijeet/Desktop/Svan_project/Svan/src/robonex_ai/robonex_ai/JoyData.idl
  Source: JoyData.hpp
  Cyclone DDS: v11.0.1

*****************************************************************/
#ifndef DDSCXX_JOYDATA_HPP_8A5F9FBD58A283015BF83257E00A70F1
#define DDSCXX_JOYDATA_HPP_8A5F9FBD58A283015BF83257E00A70F1

#include <utility>
#include <ostream>
#include <cstdint>
#include <array>

namespace xterra
{
namespace msg
{
namespace dds_
{
class JoyData_
{
private:
 uint8_t priority_ = 0;
 std::array<float, 6> axes_ = { };
 std::array<uint8_t, 12> buttons_ = { };

public:
  JoyData_() = default;

  explicit JoyData_(
    uint8_t priority,
    const std::array<float, 6>& axes,
    const std::array<uint8_t, 12>& buttons) :
    priority_(priority),
    axes_(axes),
    buttons_(buttons) { }

  uint8_t priority() const { return this->priority_; }
  uint8_t& priority() { return this->priority_; }
  void priority(uint8_t _val_) { this->priority_ = _val_; }
  const std::array<float, 6>& axes() const { return this->axes_; }
  std::array<float, 6>& axes() { return this->axes_; }
  void axes(const std::array<float, 6>& _val_) { this->axes_ = _val_; }
  void axes(std::array<float, 6>&& _val_) { this->axes_ = std::move(_val_); }
  const std::array<uint8_t, 12>& buttons() const { return this->buttons_; }
  std::array<uint8_t, 12>& buttons() { return this->buttons_; }
  void buttons(const std::array<uint8_t, 12>& _val_) { this->buttons_ = _val_; }
  void buttons(std::array<uint8_t, 12>&& _val_) { this->buttons_ = std::move(_val_); }

  bool operator==(const JoyData_& _other) const
  {
    (void) _other;
    return priority_ == _other.priority_ &&
      axes_ == _other.axes_ &&
      buttons_ == _other.buttons_;
  }

  bool operator!=(const JoyData_& _other) const
  {
    return !(*this == _other);
  }

};

std::ostream& operator<<(std::ostream& os, ::xterra::msg::dds_::JoyData_ const& rhs);

} //namespace dds_

} //namespace msg

} //namespace xterra

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::xterra::msg::dds_::JoyData_>::getTypeName()
{
  return "xterra::msg::dds_::JoyData_";
}

template <> constexpr bool TopicTraits<::xterra::msg::dds_::JoyData_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPELIB
template<> constexpr unsigned int TopicTraits<::xterra::msg::dds_::JoyData_>::type_map_blob_sz() { return 342; }
template<> constexpr unsigned int TopicTraits<::xterra::msg::dds_::JoyData_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::xterra::msg::dds_::JoyData_>::type_map_blob() {
  alignas(4) static const uint8_t blob[] = {
 0x72,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x91,  0xc5,  0xa8,  0xe0,  0xb6,  0x32,  0x76, 
 0x4d,  0x1d,  0xec,  0x17,  0xa5,  0x12,  0x42,  0x00,  0x5a,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x4a,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0d,  0xb9,  0x88,  0x29,  0x5c,  0x00, 
 0x16,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x90,  0xf3,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x06,  0x09,  0x42,  0xb4,  0x7e,  0xed,  0x00,  0x00,  0x16,  0x00,  0x00,  0x00, 
 0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x90,  0xf3,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x0c,  0x0d,  0x02,  0x63,  0x4e,  0xff,  0x00,  0x00,  0xb2,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0xf2,  0x8d,  0xce,  0x38,  0x29,  0x12,  0x23,  0x94,  0x50,  0x19,  0x63,  0x7c,  0x7c,  0x00,  0x44,  0x00, 
 0x9a,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00,  0x24,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x1c,  0x00,  0x00,  0x00,  0x78,  0x74,  0x65,  0x72,  0x72,  0x61,  0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x3a, 
 0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x4a,  0x6f,  0x79,  0x44,  0x61,  0x74,  0x61,  0x5f,  0x00, 
 0x6a,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x17,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x0d,  0x00,  0x09,  0x00,  0x00,  0x00,  0x70,  0x72,  0x69,  0x6f,  0x72,  0x69,  0x74,  0x79, 
 0x00,  0x00,  0x00,  0x00,  0x1f,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x90,  0xf3, 
 0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x06,  0x09,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00, 
 0x61,  0x78,  0x65,  0x73,  0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x90,  0xf3,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x0c,  0x0d,  0x00,  0x00, 
 0x08,  0x00,  0x00,  0x00,  0x62,  0x75,  0x74,  0x74,  0x6f,  0x6e,  0x73,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x8d,  0xce,  0x38,  0x29,  0x12,  0x23,  0x94, 
 0x50,  0x19,  0x63,  0x7c,  0x7c,  0x00,  0x44,  0xf1,  0x91,  0xc5,  0xa8,  0xe0,  0xb6,  0x32,  0x76,  0x4d, 
 0x1d,  0xec,  0x17,  0xa5,  0x12,  0x42, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::xterra::msg::dds_::JoyData_>::type_info_blob() {
  alignas(4) static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x91,  0xc5,  0xa8,  0xe0,  0xb6,  0x32,  0x76,  0x4d,  0x1d,  0xec,  0x17, 
 0xa5,  0x12,  0x42,  0x00,  0x5e,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x8d,  0xce,  0x38,  0x29,  0x12,  0x23,  0x94,  0x50,  0x19,  0x63,  0x7c, 
 0x7c,  0x00,  0x44,  0x00,  0x9e,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPELIB

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::xterra::msg::dds_::JoyData_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::xterra::msg::dds_::JoyData_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::xterra::msg::dds_::JoyData_);

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
const propvec &get_type_props<::xterra::msg::dds_::JoyData_>();

namespace {
  static const volatile propvec &properties___xterra__msg__dds___JoyData_ = get_type_props<::xterra::msg::dds_::JoyData_>();
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::xterra::msg::dds_::JoyData_& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.priority()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!write(streamer, instance.axes()[0], instance.axes().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!write(streamer, instance.buttons()[0], instance.buttons().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::xterra::msg::dds_::JoyData_& instance, key_mode key) {
  const auto &props = get_type_props<::xterra::msg::dds_::JoyData_>();
  str.set_mode(cdr_stream::stream_mode::write, key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::xterra::msg::dds_::JoyData_& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.priority()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!read(streamer, instance.axes()[0], instance.axes().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!read(streamer, instance.buttons()[0], instance.buttons().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::xterra::msg::dds_::JoyData_& instance, key_mode key) {
  const auto &props = get_type_props<::xterra::msg::dds_::JoyData_>();
  str.set_mode(cdr_stream::stream_mode::read, key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::xterra::msg::dds_::JoyData_& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.priority()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!move(streamer, instance.axes()[0], instance.axes().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!move(streamer, instance.buttons()[0], instance.buttons().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::xterra::msg::dds_::JoyData_& instance, key_mode key) {
  const auto &props = get_type_props<::xterra::msg::dds_::JoyData_>();
  str.set_mode(cdr_stream::stream_mode::move, key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::xterra::msg::dds_::JoyData_& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.priority()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!max(streamer, instance.axes()[0], instance.axes().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!max(streamer, instance.buttons()[0], instance.buttons().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::xterra::msg::dds_::JoyData_& instance, key_mode key) {
  const auto &props = get_type_props<::xterra::msg::dds_::JoyData_>();
  str.set_mode(cdr_stream::stream_mode::max, key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_JOYDATA_HPP_8A5F9FBD58A283015BF83257E00A70F1
